apiVersion: v1
data:
  configManagementPlugins: |-
    - name: argocd-vault-replacer
      generate:
        command: ["argocd-vault-replacer"]
    - name: kustomize-argocd-vault-replacer
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build . | argocd-vault-replacer"]
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
